" Some interesting settings I'm using were found in:
"  - https://github.com/rzhw/dotfiles/blob/master/vim/vimrc
execute pathogen#infect()

let mapleader = ","

" put all backup and swap files in the tmp directory and include the path
" (trailing double slash) so duplicate names don't clash
set backupdir=~/.vim/tmp//
set directory=~/.vim/tmp//

"set number      " Line numbers
set ruler       " Show current line number and char
set backspace=2 " Conventional backspace behaviour
set scrolloff=3

set encoding=utf-8
set laststatus=2

syntax on
filetype plugin indent on

set tabstop=4 shiftwidth=4 smarttab
set autoindent smartindent

" custom status line from
"  http://www.wezm.net/technical/2008/09/pimping-vim-on-windows/
"  Not sure I love it, so commenting it out -mjl
"set laststatus=2
"set statusline=%&lt;%f\ %m%a%=%([%R%H%Y]%)\ %-19(%3l\ of\ %L,%c%)%P
"set showcmd
